version: '3'
services:
   app:
    build: ./
    user: root
    volumes:
      - ./:/app
    working_dir: /app
    env_file: .env
    ports:
      - "8080:8080"
    command: jupyter lab --ip=0.0.0.0 --allow-root --NotebookApp.token='' --port=8080
